
name: 'Unit Tests'

on: push

jobs:
  # Run unit tests via Node native test runner
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test:unit